services:
  websockets:
    build: ./websocket_server
    container_name: fastuga-websockets
    ports:
      - "8080:8080"
  frontend:
    build: ./fastuga-vue
    container_name: fastuga-frontend
    ports:
      - "5174:5174"
  database:
    image: mysql:latest
    container_name: fastuga-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-fastuga_db}
      MYSQL_USER: ${DB_USERNAME:-database_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
    volumes:
      - fastuga_db_data:/var/lib/mysql
  api:
    build: ./fastuga-laravel
    container_name: fastuga-api
    ports:
      - "8081:8081"
    depends_on:
      - database
    volumes:
      - fastuga_laravel_storage:/var/www/html/storage
volumes:
  fastuga_db_data:
  fastuga_laravel_storage:
