services:
  websockets:
    build: ./websocket_server
    container_name: fastuga-websockets
    ports:
      - "8080:8080"
  frontend:
    build: ./fastuga-vue
    container_name: fastuga-frontend
    ports:
      - "5174:5174"
  api:
    build: ./fastuga-laravel
    container_name: fastuga-api
    ports:
      - "8081:8081"
    volumes:
      - fastuga_laravel_storage:/var/www/html/storage
volumes:
  fastuga_laravel_storage:
